baseURL = 'https://gabrielcasilva.github.io'
languageCode = 'pt-br'
title = 'gabrielcasilva'
paginate = 6

[params]
  description = 'blog pessoal sobre estudo de computação de tecnologias'

[taxiomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
