baseURL = 'https://gabrielcasilva.github.io'
languageCode = 'pt-br'
title = 'gabrielcasilva'
pagination.pagerSize = 6

[params]
  lang = 'pt-br'
  description = 'blog pessoal sobre estudo de computação de tecnologias'
  [params.paths]
    github = 'https://github.com/GabrielCASilva'
    linkedin = 'https://www.linkedin.com/in/gabrielcarvalho01/'

[taxiomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 2

[build]
  [build.buildStats]
    enable = true
