baseURL = 'https://gabrielcasilva.github.io'
languageCode = 'pt-br'
title = 'gabrielcasilva'
pagination.pagerSize = 6

[params]
  fingerprint = true
  lang = 'pt-br'
  description = 'blog pessoal sobre estudo de computação de tecnologias'
  [params.paths]
    github = 'https://github.com/GabrielCASilva'
    linkedin = 'https://www.linkedin.com/in/gabrielcarvalho01/'

[taxiomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 2

[build]
  [build.buildStats]
    enable = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      connect-src 'self' localhost:1313; 
      font-src 'self' localhost:1313; 
      img-src 'self' localhost:1313; 
      script-src-elem 'nonce-randomString' 'self' localhost:1313; 
      style-src-attr 'nonce-randomString' 'self' localhost:1313; 
      style-src-elem 'self'; 
    """    
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = """
      vibrate=(), 
      geolocation=(), 
      midi=(), 
      notifications=(), 
      push=(), 
      sync-xhr=(), 
      microphone=(), 
      camera=(), 
      magnetometer=(), 
      gyroscope=(), 
      speaker=(), 
      vibrate=(), 
      fullscreen=(), 
      payment=()
    """




