baseURL = 'https://gabrielcasilva.github.io'
languageCode = 'pt-br'
title = 'gcarvalho'

[params]
  description = 'blog pessoal sobre estudo de computação de tecnologias'
  pagination = 6

[taxiomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
  [[menus.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
